version: '3.9'

services:

  postgres:
    image: covid-dashboard-postgres:v1
    environment:
      POSTGRES_USER: covid
      POSTGRES_PASSWORD: covid
      POSTGRES_DB: covid
    ports:
      - 5432:5432