version: '3.9'

services:

  postgres:
    image: yhpark90/covid-dashboard-postgres:v5
    environment:
      POSTGRES_USER: covid
      POSTGRES_PASSWORD: covid
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
    driver: local